---
# add two lines to mozilla profile's prefs.js if not there: 
# user_pref("gfx.webrender.all", true);
# user_pref("layers.acceleration.force-enabled", true);
# /home/{{ username }}/.mozilla/firefox/75u792nw.default-release/prefs.js

- name: Set path
  shell: "echo /home/{{ username }}/.mozilla/firefox/75u792nw.default-release/prefs.js"
  register: mozilla_prefs_path

- name: Check for gfx hardware acceleration
  shell: "grep -c '^gfx.webrender' {{ mozilla_prefs_path.stdout }} || true"
  register: gfx_grep

- name: Enable gfx hardware acceleration
  lineinfile:
    dest: "{{ mozilla_prefs_path.stdout }}"
    line: 'user_pref("gfx.webrender.all", true);'
  when: gfx_grep.stdout == "0"

- name: Check for layers hardware acceleration
  shell: "grep -c '^layers.acceleration' {{ mozilla_prefs_path.stdout }} || true"
  register: layers_grep

- name: Enable layers hardware acceleration
  lineinfile:
    dest: "{{ mozilla_prefs_path.stdout }}"
    line: 'user_pref("layers.acceleration.force-enabled", true);'
  when: layers_grep.stdout == "0"

- name: Download extensions
  get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ username }}/Downloads/{{ item.name | basename }}"
    mode: '0644'
  with_items: "{{ firefox_extensions }}"

- name: Ensure Firefox extensions directory exists
  file:
    path: "/usr/lib/firefox-addons/extensions"
    state: directory
    mode: '0755'

- name: Install extensions
  copy:
    src: "/home/{{ username }}/Downloads/{{ item.name | basename }}"
    dest: "/usr/lib/firefox-addons/extensions/{{ item.id }}.xpi"
    mode: '0644'
    remote_src: yes
  with_items: "{{ firefox_extensions }}"
