---
# add two lines to mozilla profile's prefs.js if not there: 
# user_pref("gfx.webrender.all", true);
# user_pref("layers.acceleration.force-enabled", true);
# /home/{{ username }}/.mozilla/firefox/75u792nw.default-release/prefs.js

- name: Set path
  shell: "echo /home/{{ username }}/.mozilla/firefox/75u792nw.default-release/prefs.js"
  register: mozilla_prefs_path

- name: Enable gfx hardware acceleration
  lineinfile:
    dest: "{{ mozilla_prefs_path.stdout }}"
    line: 'user_pref("gfx.webrender.all", true);'

- name: Enable layers hardware acceleration
  lineinfile:
    dest: "{{ mozilla_prefs_path.stdout }}"
    line: 'user_pref("layers.acceleration.force-enabled", true);'

- name: Download extensions
  get_url:
    url: "{{ item.url }}"
    dest: "/home/{{ username }}/Downloads/{{ item.name | basename }}"
    mode: '0644'
  with_items: "{{ firefox_extensions }}"

- name: Ensure Firefox extensions directory exists
  file:
    path: "/usr/lib/firefox-addons/extensions"
    state: directory
    mode: '0755'

- name: Install extensions
  copy:
    src: "/home/{{ username }}/Downloads/{{ item.name | basename }}"
    dest: "/usr/lib/firefox-addons/extensions/{{ item.id }}.xpi"
    mode: '0644'
    remote_src: yes
  with_items: "{{ firefox_extensions }}"

#  "CookieAutoDelete@kennydo.com","enabled":false}]}
#  (.+)$
- name: Enable extensions
  replace:
    path: "/home/{{ username }}/.mozilla/firefox/75u792nw.default-release/extension-settings.json"
    after: '{{ item.id }}","enabled":'
    before: '}]}'
    regexp: 'false'
    replace: 'true'
  with_items: "{{ firefox_extensions }}"

- name: Enable dark mode
  lineinfile:
    dest: "{{ mozilla_prefs_path.stdout }}"
    line: 'user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");'
