---
- name: Setup Ubuntu
  hosts: localhost
  become: yes
  become_user: root

  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no

  roles:
    - role: add-repositories
    - role: update
    - role: install-packages
    - role: install-drivers
    - role: setup-vscode
    - role: setup-firefox
    - role: setup-fonts
    - role: setup-dns
    - role: setup-google-drive
    - role: setup-gnome
      become: no
    - role: setup-tmux
      vars:
        tmux_config:
          global:
            - comment: "Add sensible to list of TPM plugins"
              commands:
                - "set": "-g @plugin 'tmux-plugins/tpm'"
                  "set-option": "-g @plugin 'tmux-plugins/tmux-sensible'"
    - role: update
    - role: clean
    - role: notify-reboot
