# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'rebuild fonts cache'
  become: yes
  shell: 'fc-cache -v -f'