---
- name: Run 'apt-get update' as a separate step
  apt:
    update_cache: yes

- name: Update all apt packages
  apt:
    name: "*"
    state: latest

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes
