---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes
