---
- name: apt-get update
  apt:
    update_cache: yes
  register: updated_results
  changed_when: '"Updated" in updated_results'

- name: apt update
  apt:
    name: "*"
    state: latest

- name: apt upgrade
  apt:
    upgrade: dist
    force_apt_get: yes
