---
- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/{{ username }}/.wallpaper.jpg
  become: no

- name: Set GNOME Wallpaper
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ username }}/.wallpaper.jpg'"
  become: no

- name: Copy lockscreen file
  copy: src=files/lockscreen.jpg dest=/home/{{ username }}/.lockscreen.jpg
  become: no

- name: Set lock screen background
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/{{ username }}/.lockscreen.jpg'"
  become: no

- name: Set GTK theme
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc Dark'"
  become: no
