---
- name: Replace vim dot_files
  copy:
    src: "files/"
    dest: "/home/{{ username }}/"
    directory_mode:
  tags:
    - dircontent

- name: Ensure .vim/{autoload,bundle} directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "/home/{{ username }}/.vim"
    - "/home/{{ username }}/.vim/autoload"
    - "/home/{{ username }}/.vim/bundle"

- name: Ensure Pathogen is in place
  get_url:
    dest: "/home/{{ username }}/.vim/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim

- name: Deploy plugins
  git:
    dest: "/home/{{ username }}/.vim/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
    - name: vim-airline
      url: https://github.com/vim-airline/vim-airline
    - name: nerdtree
      url: https://github.com/preservim/nerdtree
    - name: fzf-vim
      url: https://github.com/junegunn/fzf.vim
    - name: vim-gitgutter
      url: https://github.com/airblade/vim-gitgutter
    - name: vim-fugitive
      url: https://github.com/tpope/vim-fugitive
    - name: vim-floaterm
      url: https://github.com/voldikss/vim-floaterm
