---
- name: Check if servers are already added
  lineinfile:
    backup: true
    path: "/etc/resolv.conf"
    regexp: '^nameserver 8.8.8.8'
    state: absent
  check_mode: true
  register: dns_servers_check
  changed_when: false
 
- name: Insert first nameserver if missing
  lineinfile:
    dest: "/etc/resolv.conf"
    line: 'nameserver 8.8.8.8'
  when: dns_servers_check.found == 0

- name: Insert second nameserver if missing
  lineinfile:
    dest: "/etc/resolv.conf"
    line: 'nameserver 8.8.4.4'
  when: dns_servers_check.found == 0
  
- name: Restart resolvconf and resolved when there was a DNS change
  include: "{{ role_path }}/handlers/main.yml"
  when: dns_servers_check.found == 0
